name: v8-cmake

on:
  push:
  pull_request:
    paths:
      - 'CMakeLists.txt'
      - 'cmake/**'
      - 'v8/**'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-20.04, ubuntu-22.04]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v2
      - name: setup
        run: cmake -E make_directory ${{runner.workspace}}/build
      - name: configure
        run: cmake ${{runner.workspace}}/v8-cmake
        working-directory: ${{runner.workspace}}/build
      - name: build
        run: cmake --build ${{runner.workspace}}/build -j 2
